#!/usr/bin/env bash
set -x

# Install globaly files
cp -r global/.config $HOME/
cp -r global/.zshrc $HOME/

# Android Termux
if echo $HOME | grep -q "/data/data/com.termux"; then
  apt update
  apt install -y zsh nodejs git gnupg gh golang neovim wget curl neofetch jq clang make htop unzip zip tsu screen
  cp -rf linux/.termux $HOME/
  cp -rf linux/neofetch $HOME/.config/

# Gnu/Linux
elif [[ $OSTYPE == "linux-gnu" ]]; then
  sudo apt update
  sudo apt install -y neovim git zsh wget curl neofetch jq clang make htop unzip zip  screen
  wget -qO- https://raw.githubusercontent.com/Sirherobrine23/DebianNodejsFiles/main/debianInstall.sh | sudo bash
  cp -rf linux/neofetch $HOME/.config/

# End
fi

if [[ ! -d "$HOME/.oh-my-zsh/" ]]; then
  alias chsh=""
  yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

if [[ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]];then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
fi
if [[ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]];then
  git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
fi
